title: "Mukti Subedi"
author: "Mukti Subedi"
description: "PhD Candidte at Texas Tech University <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_social: true          # show site descrpt ion and social links in the footer
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title : Home Change, icon: home}
  - {file: "README.md", About me, icon: address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:suvedimukti@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/suvedimukti"}
  - {title: Twitter, icon: Twitter, url: "https://twitter.com/suvedimukti1"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
